apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: weatherforecast-steeltoe
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: weatherforecast-steeltoe
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/kalkube/weatherforecast-steeltoe.git 
      ref:
        branch: master
